# Generated by Django 6.0 on 2026-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallettransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10),
        ),
    ]
