# Generated by Django 6.0 on 2026-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_commissionconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionconfig',
            options={'ordering': ['-start_date'], 'verbose_name': 'Commission Config', 'verbose_name_plural': 'Commission Configs'},
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Commission end datetime (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g. 10.00 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='start_date',
            field=models.DateTimeField(help_text='Commission start datetime'),
        ),
    ]
